-- Startup config

require('startup').setup({
	title_section = {
		type = 'text',
		align = 'center',
		fold_section = false,
		title = 'Header',
		margin = 5,
		content = {
			[[                         __    _                                   ]],
			[[                    _wr""        "-q__                             ]],
			[[                 _dP                 9m_                           ]],
			[[               _#P                     9#_                         ]],
			[[              d#@                       9#m                        ]],
			[[             d##                         ###                       ]],
			[[            J###                         ###L                      ]],
			[[            {###K                       J###K                      ]],
			[[            ]####K      ___aaa___      J####F                      ]],
			[[        __gmM######_  w#P""   ""9#m  _d#####Mmw__                  ]],
			[[     _g##############mZ_         __g##############m_               ]],
			[[   _d####M@PPPP@@M#######Mmp gm#########@@PPP9@M####m_             ]],
			[[  a###""          ,Z"#####@" '######"\g          ""M##m            ]],
			[[ J#@"             0L  "*##     ##@"  J#              *#K           ]],
			[[ #"               `#    "_gmwgm_~    dF               `#_          ]],
			[[7F                 "#_   ]#####F   _dK                 JE          ]],
			[[]                    *m__ ##### __g@"                   F          ]],
			[[                       "PJ#####LP"                                 ]],
			[[ `                       0######_                      '           ]],
			[[                       _0########_                                 ]],
			[[     .               _d#####^#####m__              ,               ]],
			[[      "*w_________am#####P"   ~9#####mw_________w*"                ]],
			[[          ""9@#####@M""           ""P@#####@M""                    ]],
		},
		highlight = 'Statement',
		default_color = '',
		oldfiles_amount = 0,
	},
	mappings_section = {
		type = 'mapping',
		align = 'center',
		fold_section = false,
		title = 'Mappings',
		margin = 5,
		content = {
			{' Load Last Session', 'lua require("persistence").load({last=true})', '<leader>ql'},
			{' Find File', 'lua require("telescope").extensions.frecency.frecency()', '<leader>sf'},
			{' File Browser', 'NvimTreeToggle', '<leader>t'},
			{' New File', 'lua require("startup").new_file()', '<leader>nf'},
		},
		highlight = 'String',
		default_color = '',
		oldfiles_amount = 0,
	},
	oldfiles_section = {
		type = 'oldfiles',
		oldfiles_directory = false,
		align = 'center',
		fold_section = false,
		title = 'Old files',
		margin = 5,
		content = {},
		highlight = 'String',
		oldfiles_amount = 10,
	},
	options = {
	},
	mappings = {
	},
	parts = {
		'title_section',
		'mappings_section',
		'oldfiles_section',
	},
})
